#!/usr/bin/env bash

tmux has-session -t flex

# create a new session if none exists
if [ $? != 0 ]
then

  tmux new-session -s flex -n sysmon -d

  tmux split-window -t flex:1 -v
  tmux split-window -t flex:1 -h
  tmux send-keys -t flex:1.1 'htop'  C-m
  tmux send-keys -t flex:1.2 'sudo iotop' C-m
  tmux send-keys -t flex:1.3 'sudo iftop' C-m

  tmux new-window  -t flex -n ngxlog
  tmux send-keys -t flex:2 'multitail /var/log/nginx/access.log /var/log/nginx/error.log' C-m

  tmux new-window  -t flex -n applog

  tmux select-window -t flex:1

fi

# attach to the session
count=`tmux list-clients | grep flex | wc -l`
if [ $count == 0 ]
then
  # if there are no attached clients, then attach directly to the session
  tmux attach -t flex
else
  # if is an attached client, then attached using a Groups Session
  # (this enabled different clients to view different pages)
  tmux new-session -t flex -s flex$count
fi