#!/usr/bin/env bash
# should be called from tmux_console

export APP="flex-pro"

create_new_session()
{

  ABS_LOG_DIR=`cd $ABS_SRC_DIR/../log ; pwd`

  tmux new-session -s $APP -n sysmon -d

  tmux split-window -t $APP:1 -v
  tmux split-window -t $APP:1 -h
  tmux send-keys -t $APP:1.1 'htop'  C-m
  tmux send-keys -t $APP:1.2 'sudo iotop' C-m
  tmux send-keys -t $APP:1.3 'sudo iftop' C-m

  tmux new-window  -t $APP -n ngxlog
  tmux send-keys -t $APP:2 'multitail /var/log/nginx/access.log /var/log/nginx/error.log' C-m

  tmux new-window  -t $APP -n applog
  tmux send-keys -t $APP:3 "multitail $ABS_LOG_DIR/*" C-m

  tmux new-window  -t $APP -n syslinks
  tmux send-keys -t $APP:4 'syslinks'  C-m

  tmux select-window -t $APP:1

}

